import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import Navbar from "@/shard/navbar/Navbar";
// import { ThemeProvider } from "@/ThemeProvider/ThemeContext ";
import Footer from "@/shard/footer/Footer";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booster For You",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system" 
          enableSystem={true}>
          <ReduxProvider>
            <Navbar/>
            {children}
            <Footer/>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
